### PR TITLE
Streaming error handler

### LINKED ISSUE #235: Add error handler for reload streaming
**Describe the bug**
When the streaming goes down, an alert appears with a generic error message. Also, when the stream goes up again, the music doesn't start until the user closes the alert.

**To Reproduce**
1. Up local streaming server (e.g with icecast)
2. Build app link public ip for stream
3. Check reproduce stream and get down it.
4. See alert
5. Run streaming server again and check the alert doens't close and also the stream doens't start.

**Expected behavior**
When the stream goes down and up again, the app should start stream without user interaction.

### PR DESCRIPTION
**Pull request by NataliaSuarez**
## Description

**Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.**

**This PR provides:**
-   Added NoStreamming component
-   Added streaming mesagges translations(es, en, pt)
-   Added playing status and streaming status to store
-   Updated Live and Home components with new state.

Fixes #235 

## Type of change

**Please delete options that are not relevant.**

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x] This change requires a documentation update

## How Has This Been Tested?

**Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce the cases. Please also list any relevant details for your test configuration**

**Instructions:**

**1.** Up streaming local server (e.g with icecast)
**2.** Build an app with your public ip for stream
**3.** Play live
**4.** Get down the streaming
**5.** Check the NoStreaming component shows and then reload the streaming showing loading icon. (NoStreaming component should often display again and reload again)
**6.** Up streaming local server again

**Expected result:** Live component re-starts streaming without user interaction.

## Checklist:

> The following options in **bold** are required for a PR approval. Please check the boxes only if necessary, it help us minimizing the reviewing process.

-   [x] **I have performed a self-review of my own code**
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] **My changes generate no new warnings**
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] **New and existing unit tests pass locally with my changes**

### CODE REVIEW

File: app/components/Home.vue [hunk 1]
```diff
@@ -6,12 +6,13 @@
       </StackLayout>
     </ActionBar>
     <GridLayout columns="*" rows="*, auto">
-      <Live v-show="currentTab === 'Live' && connection" v-if="exists('Live')"/>
+      <Live v-show="currentTab === 'Live' && connection && streamingUp" v-if="exists('Live')"/>
       <Schedule v-show="currentTab === 'Schedule' && connection" v-if="exists('Schedule')"/>
```
Comment (FacundoMainere) [inline app/components/Home.vue:10]: I would remove the connection clause here if connection only checks for API, the only disabled tabs should be podcasts and schedule.

**Review by FacundoMainere — COMMENTED** [review]
everything works almost perfectly, please address this two comments and it should be ready

9d0984d9-fe31-4b05-ab80-e0ef02c4c6fc
I should be seeing an "human readable" error message, with spaces. Right?

**Review by FacundoMainere — APPROVED** [review]
awesome work
